### ISSUE TITLE
Browserify verify-pdf

### ISSUE THREAD

**Issue by rushglen** [ninja-labs-tech/verify-pdf#42]
I'm using Browserify and trying to verify the signature in the browser.
Using fileReader I create an arraybuffer and then in the browerified node package
convert to a buffer before passing it to verifyPDF().
Using a valid signed pdf I get the following error: 'Unknown message digest digestAlgorithm'
I've extracted the digestAlgorithm at verifyPDF.js:

`H\u0001e\u0003\u0004\u0002\u0001

I think this is an encoding problem.

The signature:

0\u0006H\u0006\t*H÷\r\u0001\u0007\u0002 \u000690\u00065\u0002\u0001\u00011\u000f0\r\u0006\t`H\u0001e\u0003\u0004\u0002\u0001\u0005\u00000\u000b\u0006\t*H÷\r\u0001\u0007\u0001 \u0003ä0\u0003à0\u0002È \u0003\u0002\u0001\u0002\u0002\t\u0000¥\nÌS(·`Æ0\r\u0006\t*H÷\r\u0001\u0001\u000b\u0005\u000001\u000b0\t\u0006\u0003U\u0004\u0006\u0013\u0002BG1\u00130\u0011\u0006\u0003U\u0004\b\f\nSome-State1\u00120\u0010\u0006\u0003U\u0004\u0007\f\tSome City1\u00150\u0013\u0006\u0003U\u0004\n\f\fSome Company1\u00100\u000e\u0006\u0003U\u0004\u0003\f\u0007signpdf1\"0 \u0006\t*H÷\r\u0001\t\u0001\u0016\u0013signpdf@example.com0 \u0017\r180808134020Z\u0018\u000f22920522134020Z01\u000b0\t\u0006\u0003U\u0004\u0006\u0013\u0002BG1\u00130\u0011\u0006\u0003U\u0004\b\f\nSome-State1\u00120\u0010\u0006\u0003U\u0004\u0007\f\tSome City1\u00150\u0013\u0006\u0003U\u0004\n\f\fSome Company1\u00100\u000e\u0006\u0003U\u0004\u0003\f\u0007signpdf1\"0 \u0006\t*H÷\r\u0001\t\u0001\u0016\u0013signpdf@example.com0\u0001\"0\r\u0006\t*H÷\r\u0001\u0001\u0001\u0005\u0000\u0003\u0001\u000f\u00000\u0001\n\u0002\u0001\u0001\u0000Ì*;­¸¹weéCÖD§a¾Oz,\u00034Õõ\u0005ôÍrl\u001d´Y8f/ôÝ¬ÒMGèãÉJïá¿\r\u001eE\u0010î^}£ãæg~ÇþÙÖV\u0000ÿû(ï.2x?§\t{ÀûÊp\u00151D®KGaI×\u000eFPJY¦\f\u0003i¸\u0012¾à¸=y}û]V4ÿ\u0002N7ÝÇ|ÎíL# J¥JüfH\u001cÎV\"\u0016ó\u001cûfa%<<¯»ï4{&\f\u001a¬áÅ%\u0002d»÷\u0018X\u0000Ât \u0001(F\u0018zì\f+×øf´E)iõÂØÔ\u0006¿÷ÿ°\u0011ÑyÍ.<¹Â\u0013iO@8äP<jsX×ÀÞ\u001eðµò³ç³\b\u001düQô\n={äTò=·_\u0002\u0003\u0001\u0000\u0001£S0Q0\u001d\u0006\u0003U\u001d\u000e\u0004\u0016\u0004\u0014Kkw\u0013¿ÿeû&àÓ>d\u0010üÊ0\u001f\u0006\u0003U\u001d#\u0004\u00180\u0016\u0014Kkw\u0013¿ÿeû&àÓ>d\u0010üÊ0\u000f\u0006\u0003U\u001d\u0013\u0001\u0001ÿ\u0004\u00050\u0003\u0001\u0001ÿ0\r\u0006\t*H÷\r\u0001\u0001\u000b\u0005\u0000\u0003\u0001\u0001\u0000\u0003\rÿ\u0018þG\u0006(#ýå\tä¹F!d¯iâ½ôÆ§Ç{>Hì\u0011x\u0019Îá¶ÀRá#\u0010Ï>?A\u0013¨«Mù«5ó)\u000f% \u0004íh\u0015\u00165}û`æøe\u0006)ù\u0014°\b}]5_Kù\u0001^õfæ\r9ßª$`±CX\u0010ë1f`ÎÆ'\"ÒøÛ¿&.hv´¾\u000b\u0019dá\u0003hHU3\fvË=ëfS\u0018²f]ðxAâÆ_?I\u001d¢ÂÙæ\t¾ËJ\t@\u0014éà0¥#÷þ÷3\u0019Ù§ÁúP\u0005\u0014T\fþ{xÑ8qô\u0019åeo4À9Å:±iBñ«Ç\u0004^Åc\b3§©\u0016Í¬7jK\u000b\u0014¤\nn7.Á1\u0002(0\u0002$\u0002\u0001\u0001001\u000b0\t\u0006\u0003U\u0004\u0006\u0013\u0002BG1\u00130\u0011\u0006\u0003U\u0004\b\f\nSome-State1\u00120\u0010\u0006\u0003U\u0004\u0007\f\tSome City1\u00150\u0013\u0006\u0003U\u0004\n\f\fSome Company1\u00100\u000e\u0006\u0003U\u0004\u0003\f\u0007signpdf1\"0 \u0006\t*H÷\r\u0001\t\u0001\u0016\u0013signpdf@example.com\u0002\t\u0000¥\nÌS(·`Æ0\r\u0006\t`H\u0001e\u0003\u0004\u0002\u0001\u0005\u0000 i0\u0018\u0006\t*H÷\r\u0001\t\u00031\u000b\u0006\t*H÷\r\u0001\u0007\u00010/\u0006\t*H÷\r\u0001\t\u00041\"\u0004 RÉºÈú±Íyû\t\u0007bU½jßÿïNu¼y}ðiìÈ\u0012\u0001\u00020\u001c\u0006\t*H÷\r\u0001\t\u00051\u000f\u0017\r191105181350Z0\r\u0006\t*H÷\r\u0001\u0001\u0001\u0005\u0000\u0004\u0001\u0000d,§¦ZUH\u00011vâNÛ_»k\\,3\u0010\b\u000fnê»w\u0000\u001bzõ=xüá\u000536\u000b,ÂD\u0004éþÛKKD %*À¾\u0018nmÃöÞ[E}ÓÞÐ\u0001\u001czAwåoX\u001c\u0018\u001cº\\ç§D\u0015Ï[\f-mÃÐ\u0017·q´²«£Ìhä\u0015âÁ©øËb\u001dàø4 \u001cþ@\nöÅRw\u000eF]®Û\u0010¼ÝöÔ3z0é§r\u0000{ª\u0014©Ø¸FòH# `iWtkÞoô!¡\"æj²(¤¥Û'+ÀDØÇ¶Ë·¯kðG2ÁgA×nÛ\\Ôð\u001b'\u0014¦\u0010Æsü|*ÃG\u0004\u001b®}ð|4\u001eU¥¶\u0002âó c\u0014ìð\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000

**Comment by Tarek-Essam** [comment]
@rushglen we currently support node.js environment and we will release a browser version soon.

**Comment by Tarek-Essam** [comment]
@rushglen We deployed a new version that supports the browser.
