### ISSUE TITLE
Module not found: Error: Can't resolve './rootCAs'

### ISSUE THREAD

**Issue by ssuperczynski** [ninja-labs-tech/verify-pdf#43]
Following readme I tried to add library to my project:
```js
const verifyPDF = require('@ninja-labs/verify-pdf');
...

const {
    verified,
    authenticity,
    integrity,
    expired,
    meta
} = verifyPDF(signedPdfBuffer);
```

but it throws an error

> ERROR in /Users/sebastianWebstormProjects/pdf-project/node_modules/@ninja-labs/verify-pdf/lib/helpers/verification.js
> Module not found: Error: Can't resolve './rootCAs' in '/Users/sebastianWebstormProjects/WebstormProjects/pdf-project/node_modules/@ninja-labs/verify-pdf/lib/helpers'
> ERROR in /Users/sebastianWebstormProjects/WebstormProjects/pdf-project/node_modules/@ninja-labs/verify-pdf/lib/helpers/verification.js
> Module not found: Error: Can't resolve 'tls' in '/Users/sebastianWebstormProjects/WebstormProjects/pdf-project/node_modules/@ninja-labs/verify-pdf/lib/helpers'

**Comment by Tarek-Essam** [comment]
@ssuperczynski please specify the node version you are working on.

**Comment by ssuperczynski** [comment]
Actually, I just discovered in the ROADMAP.md that browser is not supported yet. I tried to run it in the Angular 8. Closing issue.

**Comment by Tarek-Essam** [comment]
@ssuperczynski yes we currently support node only but we are releasing a compatible version with the browser very soon.

**Comment by Tarek-Essam** [comment]
@ssuperczynski We deployed a new version that supports the browser.
